
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <title>Login</title>
<script type="text/javascript">
<!-- FIXME: add code to ensure we're the top-most frame -->
    if (document.getElementById('layout-doc') != null) {
        // Just refresh the page... login will take over
        window.location = window.location;
    }
</script>
    <style type="text/css">
        /* clickjacking defense */
        body { display : none; }
    </style>
<link rel="stylesheet" type="text/css" href="/theme/com/sun/webui/jsf/suntheme/css/css_master.css" />
<script type="text/javascript">
var dojoConfig={
    "isDebug": false,
    "async": true,
    "debugAtAllCosts": false,
    "paths": {"webui/suntheme": "../../com/sun/webui/jsf/suntheme/javascript"},
    "parseWidgets": false
};
</script>
<script type="text/javascript" src="/theme/META-INF/dojo/dojo.js"></script>
<script type="text/javascript" src="/theme/META-INF/json/json.js"></script>
<script type="text/javascript" src="/theme/META-INF/prototype/prototype.js"></script>
<script type="text/javascript" src="/theme/META-INF/com_sun_faces_ajax.js"></script>
<script type="text/javascript">
</script>
<link id="sun_link5" rel="stylesheet" type="text/css" href="/resource/css/css_ns6up.css" />

</head>

<body id="body3" class="LogBdy" focus="loginform.j_username" style="background-color: #FFFFFF;">
    <div id="header"class="LogTopBnd" style="background: url('/theme/com/sun/webui/jsf/suntheme/images/login/gradlogtop.jpg') repeat-x; height: 30px;"></div>
    <div class="middle" style="background-image: url(/theme/com/sun/webui/jsf/suntheme/images/login/gradlogsides.jpg);background-repeat:repeat-x;background-position:left top; background-color: #D4DCE1;">
        <div class="plugincontent" style="width1: 1px; visibility: hidden;">

<div style="height: 435px;background-image: url(/resource/community-theme/images/login-backimage-open.png);
    background-repeat:no-repeat;background-position:left top; width: 720px; margin: auto;">
    <div style="width: 460px; padding-top: 160px; margin-left: 310px;">
<img id="sun_image11" src="/resource/community-theme/images/login-product_name_open.png;jsessionid=979bb30f1e50dd3e3dcdb8b4e93d" alt="GlassFish Server Open Source Edition" height="42" width="329" border="0" />
        <form method="POST" class="form" name="loginform" action="j_security_check" autocomplete="off">
        <table role="presentation">
        <tr>
            <td><label for="Login.username" style="font-weight: bold;">User Name:</label></td>
            <td><input type="text" name="j_username" id="Login.username" tabindex="1" value="admin"></td>
        </tr>
        <tr>
            <td><label for="Login.password" style="font-weight: bold;">Password:</label>
            <td><input type="password" name="j_password" id="Login.password" tabindex="2" autocomplete="new-password">
        <tr>
            <td colspan="2" align="center">
                <input type="submit" class="Btn1"
                    value="Login"
                    title="Log In to GlassFish Administration Console" tabindex="3"
                    onmouseover="javascript: if (this.disabled==0) this.className='Btn1Hov'"
                    onmouseout="javascript: if (this.disabled==0) this.className='Btn1'"
                    onblur="javascript: if (this.disabled==0) this.className='Btn1'"
                    onfocus="javascript: if (this.disabled==0) this.className='Btn1Hov'"
                    name="loginButton" id="loginButton">
        	    <input type="hidden" name="loginButton.DisabledHiddenField" value="true" />
    	    </td>
	    </tr>
	    </table>
        </form>
    </div>
</div>

            <script type="text/javascript">
                if (true) {
                    //submitAndDisable(document.getElementById('loginButton'), 'Login');
                    document.getElementById('loginButton').form.submit();
                    //document.getElementById('loginButton').form.autocomplete="off";
                }
            </script>
        </div>
    </div>
    <div class="footer"
        style="background-image: url(/theme/com/sun/webui/jsf/suntheme/images/login/gradlogbot.jpg);background-repeat:repeat-x;background-position:left top; color: #FFFFFF; background-color: #4A5C68">
        <div id="copyright" style="width: 720px; margin-left: auto; margin-right: auto; padding: 5px;">
            <span>Copyright © 2005, 2018, Oracle and/or its affiliates. All rights reserved. </span>
        </div>
    </div>
    <script src="/resource/js/cj.js"></script>
</body>
</html>
